-- Creating notifications reference tables

CREATE TABLE CGP_REF_SUBSCRIBERS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  SUBSCRIBER_EMAIL VARCHAR2(255) NOT NULL,
  FIRST_NAME VARCHAR2(255),
  LAST_NAME VARCHAR2(255),
  DESCRIPTION VARCHAR2(255)
);
CREATE INDEX IDX_SUBSCRIBERS ON CGP_REF_SUBSCRIBERS (SUBSCRIBER_EMAIL);

CREATE TABLE CGP_REF_SUBSCRIBER_NOTIF
(
  NOTIFICATION_ID NUMBER(19) NOT NULL,
  SUBSCRIBER_ID NUMBER(19) NOT NULL
);
CREATE UNIQUE INDEX IDX_SUBSCRIBER_NOTIFICATION ON CGP_REF_SUBSCRIBER_NOTIF (NOTIFICATION_ID, SUBSCRIBER_ID);


CREATE TABLE CGP_REF_NOTIFICATIONS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  CATEGORY VARCHAR2(255) NOT NULL,
  SUBCATEGORY VARCHAR2(255),
  SUBCATEGORY_DESC VARCHAR2(255)
);
CREATE INDEX IDX_NOTIFICATIONS ON CGP_REF_NOTIFICATIONS (SUBCATEGORY);

-- populating subscribers and notifications tables
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(2,'services','01R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(3,'services','02R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(4,'services','03R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(5,'services','04R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(6,'services','05R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(7,'services','06R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(8,'services','07R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(9,'services','08R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(10,'services','09R10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(11,'services','AKR10F000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(12,'services','AKR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(13,'services','ALR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(14,'services','ASR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(15,'services','AZR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(16,'services','CAR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(17,'services','COR10F000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(18,'services','COR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(19,'services','CTR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(20,'services','DCR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(21,'services','DER10F000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(22,'services','FLR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(23,'services','GUR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(24,'services','IAR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(25,'services','IDR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(26,'services','IDR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(27,'services','JAR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(28,'services','KSR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(29,'services','LAR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(30,'services','MAR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(31,'services','MAR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(32,'services','MIR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(33,'services','MNR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(34,'services','MPR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(35,'services','MSR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(36,'services','MTR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(37,'services','MWR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(38,'services','NCR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(39,'services','NDR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(40,'services','NER10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(41,'services','NHR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(42,'services','NMR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(43,'services','NMR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(44,'services','NVR10000I', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(45,'services','NYR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(46,'services','OKR10F000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(47,'services','OKR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(48,'services','ORR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(49,'services','PRR100000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(50,'services','RIR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(51,'services','SDR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(52,'services','TXR10F000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(53,'services','TXR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(54,'services','UTR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(55,'services','VAR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(56,'services','VTR10F000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(57,'services','WAR10F000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(58,'services','WAR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(59,'services','WIR10I000', 'MGP number');
INSERT INTO CGP_REF_NOTIFICATIONS(ID, CATEGORY, SUBCATEGORY, SUBCATEGORY_DESC) VALUES(60,'services','WYR10I000', 'MGP number');

INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(1,'nmfs.pgp.waorcanois@noaa.gov', 'NMFS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(2,'nmfs.gar.msgp@noaa.gov', 'NMFS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(3,'nmfs.ser.esa.consultations@noaa.gov', 'NMFS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(4,'jerry_ziewitz@fws.gov','Jerry', 'Ziewitz', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(5,'annette_trowbridge@fws.gov','Annette', 'Trowbridge', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(6,'maria_boroja@fws.gov','Maria', 'Boroja', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(7,'mark_sattelberg@fws.gov','Mark', 'Sattelberg', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(8,'drew_crane@fws.gov','Drew', 'Crane', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(9,'dawn_bruns@fws.gov','Dawn', 'Bruns', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(10,'efhesaconsult@noaa.gov', 'NMFS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(11,'carrie_marr@fws.gov','Carrie', 'Marr', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(12,'damian_higgins@fws.gov','Damian', 'Higgins', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(13,'barb_osmundson@fws.gov','Barb', 'Osmundson', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(14,'laura_archuleta@fws.gov','Laura', 'Archuleta', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(15,'brian_sanchez@fws.gov','Brian', 'Sanchez', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(16,'trevor_clark@fws.gov','Trevor', 'Clark', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(17,'chris_reighn@fws.gov','Chris', 'Reighn', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(18,'nmfswcr.srbo@noaa.gov', 'NMFS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(19,'gibran_sulieman@fws.gov','Gibran', 'Sulieman', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(20,'john_miesner@fws.gov','John', 'Miesner', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(21,'amy_trahan@fws.go','Amy', 'Trahan', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(22,'karen_nelson@fws.gov','Karen', 'Nelson', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(23,'david_rouse@fws.gov','David', 'Rouse', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(24,'jessica_n_johnson@fws.gov','Jessica', 'Johnson', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(25,'amanda_ciurej@fws.gov','Amanda', 'Ciurej', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(26,'newengland@fws.gov', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(27,'nmesfo@fws.gov', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(28,'okprojectreview@fws.gov', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(29,'craig_rowland@fws.gov','Craig', 'Rowland', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(30,'felix_lopez@fws.gov','Felix', 'Lopez', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(31,'matt_schwarz@fws.gov','Matt', 'Schwarz', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(32,'erik_orsak@fws.gov','Erik', 'Orsak', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(33,'tanya_sommer@fws.gov','Tanya', 'Sommer', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(34,'david_doth@fws.gov','David', 'Hoth', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(35,'chuck_ardizzone@fws.gov','Chuck', 'Ardizzone', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(36,'chris_cline@fws.gov','Chris', 'Cline', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(37,'wfwoctap@fws.gov', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, FIRST_NAME, LAST_NAME, DESCRIPTION) VALUES(38,'kimberly_dickerson@fws.gov','Kimberly', 'Dickerson', 'FWS contact');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(39,'michael.monks@cgifederal.com', 'CGI tester');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(40,'lauren.dearment@cgifederal.com', 'CGI tester');
INSERT INTO CGP_REF_SUBSCRIBERS(ID, SUBSCRIBER_EMAIL, DESCRIPTION) VALUES(41,'linera.abieva@cgifederal.com', 'CGI tester');


-- populating subscriber_notifications table with data for testing
INSERT INTO CGP_REF_SUBSCRIBER_NOTIF (NOTIFICATION_ID, SUBSCRIBER_ID) VALUES (14, 39);
INSERT INTO CGP_REF_SUBSCRIBER_NOTIF (NOTIFICATION_ID, SUBSCRIBER_ID) VALUES (14, 40);
INSERT INTO CGP_REF_SUBSCRIBER_NOTIF (NOTIFICATION_ID, SUBSCRIBER_ID) VALUES (14, 41);



