update cgp_ref_mgp set IND_COUNTRY_MGP_NUMBER = 'FLR10I00E' WHERE IND_COUNTRY_MGP_NUMBER = 'FLR10I000';
update cgp_ref_npdes_seq set MGP_NUM = 'FLR10I00E' where MGP_NUM = 'FLR10I000';
update cgp_noi_form_sets set MASTER_PERMIT_NUMBER = 'FLR10I00E' WHERE MASTER_PERMIT_NUMBER = 'FLR10I000';

