insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2479,320002601, 'Mercury in fish tissue', 'Mercury in fish tissue');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2480,320002602, 'Benthic macroinvert. community', 'Benthic macroinvert. community');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2481,320002603, 'Copper, chronic', 'Copper, chronic');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2482,320002604, 'Temperature', 'Temperature');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2483,320002605, 'Cyanide, total recoverable', 'Cyanide, total recoverable');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2484,320002606, 'Cadmium, dissolved', 'Cadmium, dissolved');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2485,320002607, 'Sedimentation/Siltation', 'Sedimentation/Siltation');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2486,320002608, 'PCB in fish tissue', 'PCB in fish tissue');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2487,320002609, 'Aluminum, total rec - chronic', 'Aluminum, total rec - chronic');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2488,320002610, 'Dissolved oxygen', 'Dissolved oxygen');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2489,320002611, 'Copper, acute', 'Copper, acute');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2490,320002612, 'Zinc, acute', 'Zinc, acute');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2491,320002613, 'PCB in water column', 'PCB in water column');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2492,320002614, 'Ammonia, unionized', 'Ammonia, unionized');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2493,320002615, 'Boron, dissolved', 'Boron, dissolved');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2494,320002616, 'Arsenic, dissolved', 'Arsenic, dissolved');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2495,320002617, 'Nutrient/Eutrophication', 'Nutrient/Eutrophication');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2496,320002618, 'Thallium, dissolved', 'Thallium, dissolved');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2497,320002619, 'Lead, dissolved', 'Lead, dissolved');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2498,320002620, 'DDT in fish tissue', 'DDT in fish tissue');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2499,320002621, 'Low flow alterations', 'Low flow alterations');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2500,320002622, 'Aluminum, total rec - acute', 'Aluminum, total rec - acute');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2501,320002623, 'Uranium, dissolved', 'Uranium, dissolved');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2502,320002624, 'Total dissolved solids', 'Total dissolved solids');
insert into cgp_ref_pollutants(id, pollutant_code, pollutant_name, pollutant_srs_name) values(2503,320002625, 'Aluminum, dissolved', 'Aluminum, dissolved');
